# build react app
FROM node:alpine AS builder
WORKDIR /app
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build
EXPOSE 3000
CMD ["yarn", "run", "start"]
# setup nginx
FROM nginx:alpine
LABEL maintainer="SE2 Group H PW MiNI"
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build .
EXPOSE 80
EXPOSE $PORT
ENTRYPOINT ["nginx", "-g", "daemon off;"]