name: TESTS Frontend

on:
  pull_request:
    branches: 
      - master
      - stage/frontend

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Run the tests
      run: yarn test

    - name: Build (see if app builds)
      run: npm run build
